import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
const STAGES = ["SAMPLE", "SELECTED", "PRICE", "VERIFIED", "DELIVERED"];
export default function Hero() {
    const [stageIndex, setStageIndex] = useState(0);
    useEffect(() => {
        const id = setInterval(() => setStageIndex((i) => (i + 1) % STAGES.length), 2200);
        return () => clearInterval(id);
    }, []);
    return (_jsx("section", { className: "min-h-screen flex items-center pt-24 pb-12 px-6 bg-obsidian", children: _jsxs("div", { className: "max-w-7xl mx-auto grid md:grid-cols-2 gap-16 items-center w-full", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.18em] text-antiquegold mb-6", children: "Jewellery, reimagined" }), _jsxs("h1", { className: "font-serif text-5xl md:text-7xl leading-[0.98] text-ivory mb-6", children: ["See it.", _jsx("br", {}), "Trust it.", _jsx("br", {}), "Bring it home."] }), _jsx("p", { className: "text-parchment/80 text-base md:text-lg max-w-md mb-8 leading-relaxed", children: "Discover jewellery designs from the comfort of your home. Explore physical samples, understand the complete price, and order through trusted jewellery partners." }), _jsxs("div", { className: "flex flex-wrap gap-4", children: [_jsx("a", { href: "#book-a-visit", className: "bg-antiquegold text-obsidian px-6 py-3 text-sm uppercase tracking-wide rounded hover:bg-highlightgold transition-colors", children: "Book a Home Jewellery Visit" }), _jsx("a", { href: "#how-it-works", className: "border border-champagne/40 text-champagne px-6 py-3 text-sm uppercase tracking-wide rounded hover:border-highlightgold hover:text-highlightgold transition-colors", children: "See How It Works" })] })] }), _jsx("div", { className: "relative h-[420px] flex items-center justify-center", children: _jsxs("div", { className: "w-72 h-96 rounded-lg border border-champagne/20 bg-espresso relative overflow-hidden flex flex-col items-center justify-center", children: [_jsx(AnimatePresence, { mode: "wait", children: _jsxs(motion.div, { initial: { opacity: 0, y: 14 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -14 }, transition: { duration: 0.5 }, className: "text-center px-6", children: [_jsx("div", { className: "w-16 h-16 mx-auto mb-6 rounded-full border border-antiquegold/60 flex items-center justify-center", children: _jsx("span", { className: "w-2 h-2 rounded-full bg-highlightgold" }) }), _jsxs("p", { className: "text-xs uppercase tracking-[0.2em] text-highlightgold mb-2", children: ["Stage ", stageIndex + 1, " / ", STAGES.length] }), _jsx("p", { className: "font-serif text-2xl text-ivory", children: STAGES[stageIndex] })] }, STAGES[stageIndex]) }), _jsx("div", { className: "absolute bottom-6 flex gap-1.5", children: STAGES.map((s, i) => (_jsx("span", { className: `h-1 rounded-full transition-all duration-500 ${i === stageIndex ? "w-6 bg-highlightgold" : "w-1.5 bg-champagne/25"}` }, s))) })] }) })] }) }));
}
